### ISSUE TITLE
Add filtering method

### ISSUE THREAD

**Issue by ljchang** [cosanlab/feat#10]
- add filtering (high pass and low pass) - see nltools.data.Brain_Data example
- add detrending - (linear, quadratic, cubic) - see nltools.data.Brain_Data example

detrending could be useful if we see huge baseline shifts which could indicate baseline face location change (this sometimes happens for our head-mounted cameras where the helmet might shift in position)

**Comment by ljchang** [comment]
working on this now.

**Comment by ljchang** [comment]
I like how nilearn has conceptualized this problem and propose wrapping their [`nilearn.signal.clean` function](http://nilearn.github.io/modules/generated/nilearn.signal.clean.html#nilearn.signal.clean).

Basically, you can detrend, filter, and also denoise all in one step.

The only thing I don't like is that all of these functions are embedded in the same function. We could provide aliases if this ends up being a problem.  It seems nice to take care of all of these in one step or at different stages.

**Comment by jcheong0428** [comment]
I think something like a preprocessing function / workflow could be nice or a spm12w-ish system. 
It could be a series of flags that could be set up to run preprocessing.
 
interpolate: True, {'linear', limit=10}
demean: True
demedian: True
detrending: {'linear':True,'quadratic':False}
filtering: {highpass: , lowpass}
extract features: {'BofT', 'Mean', 'Max'}
PCA-denoising: False
etc.. 

would be almost a 1-click solution without having to chain methods (which would still be possible).

**Comment by ljchang** [comment]
we could write a function to do that too, but some of them are going to need to be chained.
At the moment, `interpolate().downsample().baseline().clean()` will work to do just about all of the main preprocessing.  As soon as we have a feature extraction method.  we should be good to go to work on data analysis.
