### ISSUE TITLE
Streamline tests

### ISSUE THREAD

**Issue by Nathaniel-Haines** [cosanlab/feat#15]
Currently, the test files have a lot of repetitive code to run each of the different imported data types (e.g. FACET vs OpenFace). There is probably a better way to streamline the code (loop over data files?)

**Comment by ljchang** [comment]
There should be a few ways to do this.  Py.test has all kinds of things to help with this.  You might look into it and see what you can find.  There are fixtures, which we are using yet and I'm pretty sure there is a straightforward way to run tests over different datasets.  TBH.  We probably don't need to run every test for each data importer.  

Typically, we can have a different test file for each module we want to test.  That's another way to minimize redundancy.

**Comment by Nathaniel-Haines** [comment]
Py.test tutorial on parameterizing tests: https://dpb.bitbucket.io/pytest-parametrization.html

**Comment by jcheong0428** [comment]
I don't think we need to repeat testing methods on each dataset. 
Testing the methods on just one should suffice and for each dataset just test the importers. 
I've shortened the tests on subclass_openface PR.

**Comment by Nathaniel-Haines** [comment]
Thanks a lot! I will close this for now.
