### ISSUE TITLE
Need a few key preprocessing methods

### ISSUE THREAD

**Issue by ljchang** [cosanlab/feat#3]
1) need to be able to interpolate data
2) need to be able to downsample
3) need to be able to normalize (demedian, demean, zscore)
4) need to be able to baseline (to a reference point, mean, or median).
5) need to be able to filter.

**Comment by jcheong0428** [comment]
Possible implementations: 

1. need to be able to interpolate data
- pandas series interpolate
2. need to be able to downsample
- refactor nltools downsample
3. need to be able to normalize (demedian, demean, zscore)
- pandas apply-transform
4. need to be able to baseline (to a reference point, mean, or median).
- pandas apply-transform
5. need to be able to filter.
- lowpass/highpass/bandpass filtering from scipy 
6. Artifact removal - for face occlusions? 
- pca remove first component

**Comment by ljchang** [comment]
Ok looks like we have most of these done.
-downsample
-upsample
-baseline (also normalize)

**Comment by ljchang** [comment]
opened up issues for the remaining ones.
